### ISSUE TITLE
[FEAT] BottomModal 컴포넌트 추가

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#42]
## Description

- BottomModal 컴포넌트 추가
  <img width="289" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/c799bcaa-fd49-45a6-a7e8-e83626b8aca4">

## To-do

- [ ] BottomModal 컴포넌트 추가

**Comment by hansol775** [comment]
bottom modal component 필요하시면 완성된 코드 드릴 수 있어요.

**Comment by chajuhui123** [comment]
@hansol775 오 감사합니다! 그렇다면 한솔님의 코드도 볼겸 공유해주실 수 있으실까요? 👀
